const express = require('express');
const http = require('http');
const { Server } = require('socket.io');
const mongoose = require('mongoose');
const cors = require('cors');
const path = require('path');
const bcrypt = require('bcryptjs');
const jwt = require('jsonwebtoken');
const axios = require('axios');
require('dotenv').config();

const app = express();
const server = http.createServer(app);
const io = new Server(server, { cors: { origin: '*', methods: ['GET','POST','PUT','DELETE'] } });

app.use(cors());
app.use(express.json());
app.use(express.static(path.join(__dirname, '../Frontend')));

mongoose.connect(process.env.MONGO_URI || 'mongodb://localhost:27017/studyup')
  .then(() => console.log('✅ MongoDB Connected'))
  .catch(err => console.log('❌ DB Error:', err.message));

const JWT_SECRET = process.env.JWT_SECRET || 'studyup_jee2027_secret';
const today = () => new Date().toISOString().split('T')[0];

// ── SCHEMAS ──────────────────────────────────────────────────
const UserSchema = new mongoose.Schema({
  name: { type: String, required: true },
  email: { type: String, required: true, unique: true },
  password: { type: String, required: true },
  weakSubject: { type: String, default: 'Physics' },
  dailyGoalHours: { type: Number, default: 8 },
  scheduleSetup: { type: Boolean, default: false },
  createdAt: { type: Date, default: Date.now }
});

const ProgressSchema = new mongoose.Schema({
  userId: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
  date: { type: String, required: true },
  studyTime: { type: Number, default: 0 },
  tasksCompleted: { type: Number, default: 0 },
  tasksTotal: { type: Number, default: 0 },
  subjectTime: { Physics: Number, Chemistry: Number, Mathematics: Number }
}, { timestamps: true });

const TaskSchema = new mongoose.Schema({
  userId: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
  title: { type: String, required: true },
  subject: { type: String, required: true },
  chapter: { type: String, default: '' },
  priority: { type: String, default: 'Medium' },
  importance: { type: String, default: 'Important' },
  timeRequired: { type: Number, default: 60 },
  pyqCount: { type: Number, default: 0 },
  dueDate: { type: String },
  completed: { type: Boolean, default: false },
  completedAt: { type: Date },
  autoGenerated: { type: Boolean, default: false }
}, { timestamps: true });

const ScheduleSchema = new mongoose.Schema({
  userId: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
  week: { type: String, required: true },
  slots: [{ day: String, startTime: String, endTime: String, subject: String, chapter: String }],
  routine: { wakeTime: String, sleepTime: String, studyHours: Number, weakSubject: String }
}, { timestamps: true });

const AchievementSchema = new mongoose.Schema({
  userId: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
  title: String, description: String, icon: { type: String, default: '🏆' },
  type: String, xp: { type: Number, default: 10 },
  earnedAt: { type: Date, default: Date.now }
});

const ChatSchema = new mongoose.Schema({
  userId: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
  role: { type: String, enum: ['user','assistant'] },
  content: String, timestamp: { type: Date, default: Date.now }
});

const MockTestSchema = new mongoose.Schema({
  userId: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
  score: Number, totalQ: Number, correct: Number, wrong: Number, skipped: Number,
  timeTaken: Number, subjectScores: { Physics: Number, Chemistry: Number, Mathematics: Number },
  completedAt: { type: Date, default: Date.now }
});

const User = mongoose.model('User', UserSchema);
const Progress = mongoose.model('Progress', ProgressSchema);
const Task = mongoose.model('Task', TaskSchema);
const Schedule = mongoose.model('Schedule', ScheduleSchema);
const Achievement = mongoose.model('Achievement', AchievementSchema);
const Chat = mongoose.model('Chat', ChatSchema);
const MockTest = mongoose.model('MockTest', MockTestSchema);

// ── AUTH MIDDLEWARE ──────────────────────────────────────────
const auth = async (req, res, next) => {
  try {
    const token = req.headers.authorization?.split(' ')[1];
    if (!token) return res.status(401).json({ error: 'No token' });
    const decoded = jwt.verify(token, JWT_SECRET);
    req.userId = decoded.id;
    next();
  } catch { res.status(401).json({ error: 'Invalid token' }); }
};

// ── HELPERS ──────────────────────────────────────────────────
async function calcStreak(userId) {
  const records = await Progress.find({ userId, studyTime: { $gt: 0 } }).sort({ date: -1 }).lean();
  if (!records.length) return 0;
  let streak = 0;
  let check = new Date(); check.setHours(0,0,0,0);
  for (const rec of records) {
    const rd = new Date(rec.date); rd.setHours(0,0,0,0);
    const diff = Math.round((check - rd) / 86400000);
    if (diff <= 1) { streak++; check = rd; } else break;
  }
  return streak;
}

async function calcRank(userId) {
  const pipeline = [
    { $group: { _id: '$userId', total: { $sum: '$studyTime' } } },
    { $sort: { total: -1 } }
  ];
  const all = await Progress.aggregate(pipeline);
  const idx = all.findIndex(u => u._id.toString() === userId.toString());
  return idx === -1 ? all.length + 1 : idx + 1;
}

async function checkAchievements(userId, streak, totalTasks, totalHours) {
  const existing = (await Achievement.find({ userId }).select('title')).map(a => a.title);
  const milestones = [
    { title: 'First Step', desc: 'Completed first task!', icon: '🎯', xp: 10, cond: totalTasks >= 1 },
    { title: 'Task Master', desc: 'Completed 10 tasks!', icon: '✅', xp: 50, cond: totalTasks >= 10 },
    { title: '3 Day Streak 🔥', desc: '3 consecutive study days', icon: '🔥', xp: 30, cond: streak >= 3 },
    { title: 'Consistency', desc: '7 days in a row!', icon: '💪', xp: 100, cond: streak >= 7 },
    { title: 'Discipline', desc: '14 days in a row!', icon: '⚡', xp: 200, cond: streak >= 14 },
    { title: 'Regular', desc: '30 days in a row!', icon: '📅', xp: 500, cond: streak >= 30 },
    { title: 'Time Master', desc: 'Studied 8+ hrs in one day!', icon: '⏰', xp: 150, cond: totalHours >= 8 },
    { title: '100 Hours Club', desc: '100 total hours studied!', icon: '🏆', xp: 300, cond: totalHours >= 100 },
  ];
  const newAchs = [];
  for (const m of milestones) {
    if (m.cond && !existing.includes(m.title)) {
      const ach = await Achievement.create({ userId, title: m.title, description: m.desc, icon: m.icon, xp: m.xp });
      newAchs.push(ach);
    }
  }
  return newAchs;
}

const JEE_CHAPTERS = {
  Physics: [
    { chapter: 'Kinematics', pyq: 8, time: 90, priority: 'High' },
    { chapter: 'Laws of Motion', pyq: 7, time: 90, priority: 'High' },
    { chapter: 'Work Energy Power', pyq: 6, time: 75, priority: 'Medium' },
    { chapter: 'Rotational Motion', pyq: 9, time: 120, priority: 'High' },
    { chapter: 'Gravitation', pyq: 5, time: 75, priority: 'Medium' },
    { chapter: 'Thermodynamics', pyq: 9, time: 90, priority: 'High' },
    { chapter: 'SHM & Waves', pyq: 10, time: 120, priority: 'High' },
    { chapter: 'Electrostatics', pyq: 12, time: 120, priority: 'High' },
    { chapter: 'Current Electricity', pyq: 11, time: 120, priority: 'High' },
    { chapter: 'Magnetic Effects', pyq: 9, time: 90, priority: 'High' },
    { chapter: 'Optics', pyq: 10, time: 90, priority: 'High' },
    { chapter: 'Modern Physics', pyq: 11, time: 90, priority: 'High' },
  ],
  Chemistry: [
    { chapter: 'Mole Concept', pyq: 8, time: 90, priority: 'High' },
    { chapter: 'Atomic Structure', pyq: 7, time: 75, priority: 'High' },
    { chapter: 'Chemical Bonding', pyq: 11, time: 90, priority: 'High' },
    { chapter: 'Chemical Equilibrium', pyq: 9, time: 90, priority: 'High' },
    { chapter: 'Ionic Equilibrium', pyq: 8, time: 90, priority: 'High' },
    { chapter: 'Electrochemistry', pyq: 9, time: 90, priority: 'High' },
    { chapter: 'Chemical Kinetics', pyq: 8, time: 90, priority: 'High' },
    { chapter: 'Coordination Compounds', pyq: 10, time: 90, priority: 'High' },
    { chapter: 'Organic Basics', pyq: 9, time: 90, priority: 'High' },
    { chapter: 'Hydrocarbons', pyq: 8, time: 90, priority: 'Medium' },
    { chapter: 'Aldehydes & Ketones', pyq: 8, time: 75, priority: 'High' },
    { chapter: 'Biomolecules', pyq: 6, time: 60, priority: 'Medium' },
  ],
  Mathematics: [
    { chapter: 'Quadratic Equations', pyq: 8, time: 90, priority: 'High' },
    { chapter: 'Complex Numbers', pyq: 9, time: 90, priority: 'High' },
    { chapter: 'Matrices & Determinants', pyq: 10, time: 90, priority: 'High' },
    { chapter: 'Permutation & Combination', pyq: 7, time: 75, priority: 'High' },
    { chapter: 'Probability', pyq: 9, time: 90, priority: 'High' },
    { chapter: 'Limits & Continuity', pyq: 8, time: 90, priority: 'High' },
    { chapter: 'Differentiation', pyq: 10, time: 90, priority: 'High' },
    { chapter: 'Integration', pyq: 14, time: 120, priority: 'High' },
    { chapter: 'Differential Equations', pyq: 8, time: 90, priority: 'High' },
    { chapter: 'Coordinate Geometry', pyq: 11, time: 90, priority: 'High' },
    { chapter: '3D Geometry', pyq: 9, time: 90, priority: 'High' },
    { chapter: 'Vectors', pyq: 8, time: 75, priority: 'High' },
  ]
};

async function autoGenerateTasks(userId) {
  const todayStr = today();
  const existing = await Task.find({ userId, dueDate: todayStr, autoGenerated: true });
  if (existing.length > 0) return; // Already generated today

  const user = await User.findById(userId);
  const dayOfWeek = new Date().getDay(); // 0=Sun, 1=Mon...
  
  // Rotate through chapters based on day
  const subjects = ['Physics', 'Chemistry', 'Mathematics'];
  const tasksToCreate = [];

  subjects.forEach((subj, si) => {
    const chapters = JEE_CHAPTERS[subj];
    const idx = (dayOfWeek + si * 4) % chapters.length;
    const ch = chapters[idx];
    
    // Extra task for weak subject
    const isWeak = subj === (user?.weakSubject || 'Physics');
    
    tasksToCreate.push({
      userId, title: `Study ${ch.chapter}`, subject: subj,
      chapter: ch.chapter, priority: ch.priority,
      importance: ch.pyq >= 10 ? 'Critical' : ch.pyq >= 7 ? 'Important' : 'Normal',
      timeRequired: ch.time, pyqCount: ch.pyq,
      dueDate: todayStr, autoGenerated: true, completed: false
    });

    if (isWeak) {
      // Extra PYQ task for weak subject
      const idx2 = (idx + 1) % chapters.length;
      const ch2 = chapters[idx2];
      tasksToCreate.push({
        userId, title: `PYQ Practice: ${ch2.chapter}`, subject: subj,
        chapter: ch2.chapter, priority: 'High',
        importance: 'Critical', timeRequired: 45, pyqCount: ch2.pyq,
        dueDate: todayStr, autoGenerated: true, completed: false
      });
    }
  });

  // Revision task
  tasksToCreate.push({
    userId, title: 'Daily Revision — Formulas & Concepts', subject: 'Physics',
    chapter: 'All Subjects', priority: 'High', importance: 'Important',
    timeRequired: 30, pyqCount: 0, dueDate: todayStr, autoGenerated: true, completed: false
  });

  await Task.insertMany(tasksToCreate);
}

// ── AUTH ROUTES ──────────────────────────────────────────────
app.post('/api/auth/register', async (req, res) => {
  try {
    const { name, email, password } = req.body;
    if (!name || !email || !password) return res.status(400).json({ error: 'All fields required' });
    if (await User.findOne({ email })) return res.status(400).json({ error: 'Email already registered' });
    const hashed = await bcrypt.hash(password, 12);
    const user = await User.create({ name, email, password: hashed });
    const token = jwt.sign({ id: user._id }, JWT_SECRET, { expiresIn: '30d' });
    res.json({ token, user: { id: user._id, name: user.name, email: user.email } });
  } catch (err) { res.status(500).json({ error: err.message }); }
});

app.post('/api/auth/login', async (req, res) => {
  try {
    const { email, password } = req.body;
    const user = await User.findOne({ email });
    if (!user) return res.status(400).json({ error: 'Invalid credentials' });
    if (!await bcrypt.compare(password, user.password)) return res.status(400).json({ error: 'Invalid credentials' });
    const token = jwt.sign({ id: user._id }, JWT_SECRET, { expiresIn: '30d' });
    // Auto generate today's tasks on login
    autoGenerateTasks(user._id).catch(console.error);
    res.json({ token, user: { id: user._id, name: user.name, email: user.email } });
  } catch (err) { res.status(500).json({ error: err.message }); }
});

app.get('/api/auth/me', auth, async (req, res) => {
  try {
    const user = await User.findById(req.userId).select('-password');
    res.json(user);
  } catch (err) { res.status(500).json({ error: err.message }); }
});

// ── PROGRESS ROUTES ──────────────────────────────────────────
app.get('/api/progress/today', auth, async (req, res) => {
  try {
    let p = await Progress.findOne({ userId: req.userId, date: today() });
    if (!p) p = { studyTime: 0, tasksCompleted: 0, tasksTotal: 0, date: today() };
    res.json(p);
  } catch (err) { res.status(500).json({ error: err.message }); }
});

app.put('/api/progress/today', auth, async (req, res) => {
  try {
    const update = req.body;
    // Only ADD time, never replace (prevents fake data)
    let p = await Progress.findOne({ userId: req.userId, date: today() });
    if (!p) {
      p = await Progress.create({ userId: req.userId, date: today(), ...update });
    } else {
      if (update.studyTime) p.studyTime = (p.studyTime || 0) + update.studyTime;
      if (update.tasksCompleted !== undefined) p.tasksCompleted = update.tasksCompleted;
      if (update.tasksTotal !== undefined) p.tasksTotal = update.tasksTotal;
      await p.save();
    }
    io.to(req.userId.toString()).emit('progress_update', p);
    res.json(p);
  } catch (err) { res.status(500).json({ error: err.message }); }
});

app.get('/api/progress/stats', auth, async (req, res) => {
  try {
    const history = await Progress.find({ userId: req.userId }).sort({ date: -1 }).limit(90).lean();
    const streak = await calcStreak(req.userId);
    const rank = await calcRank(req.userId);
    const totalStudyTime = history.reduce((s, p) => s + (p.studyTime || 0), 0);
    const totalTasks = history.reduce((s, p) => s + (p.tasksCompleted || 0), 0);
    const daysStudied = history.filter(p => p.studyTime > 0).length;
    const avgSuccess = history.length
      ? history.filter(p => p.tasksTotal > 0).reduce((s, p) => s + ((p.tasksCompleted / p.tasksTotal) * 100), 0) / Math.max(1, history.filter(p => p.tasksTotal > 0).length)
      : 0;
    
    // Check achievements
    const totalHours = Math.round(totalStudyTime / 60);
    const newAchs = await checkAchievements(req.userId, streak, totalTasks, totalHours);
    newAchs.forEach(a => io.to(req.userId.toString()).emit('achievement_unlocked', a));

    res.json({ streak, rank, totalStudyTime, totalTasks, daysStudied, avgSuccess: Math.round(avgSuccess) });
  } catch (err) { res.status(500).json({ error: err.message }); }
});

app.get('/api/progress/history', auth, async (req, res) => {
  try {
    const days = parseInt(req.query.days) || 7;
    const history = await Progress.find({ userId: req.userId }).sort({ date: -1 }).limit(days).lean();
    res.json(history);
  } catch (err) { res.status(500).json({ error: err.message }); }
});

// ── TASK ROUTES ──────────────────────────────────────────────
app.get('/api/tasks', auth, async (req, res) => {
  try {
    const { date, subject } = req.query;
    let query = { userId: req.userId };
    if (subject) query.subject = subject;
    if (date) query.dueDate = date;
    const tasks = await Task.find(query).sort({ priority: 1, pyqCount: -1, createdAt: 1 });
    res.json(tasks);
  } catch (err) { res.status(500).json({ error: err.message }); }
});

app.post('/api/tasks', auth, async (req, res) => {
  try {
    const task = await Task.create({ ...req.body, userId: req.userId });
    io.to(req.userId.toString()).emit('task_added', task);
    res.json(task);
  } catch (err) { res.status(500).json({ error: err.message }); }
});

app.put('/api/tasks/:id', auth, async (req, res) => {
  try {
    const task = await Task.findOneAndUpdate(
      { _id: req.params.id, userId: req.userId },
      { $set: req.body }, { new: true }
    );
    if (req.body.completed) {
      const todayStr = today();
      const allTasks = await Task.find({ userId: req.userId, dueDate: todayStr });
      const done = allTasks.filter(t => t.completed).length;
      await Progress.findOneAndUpdate(
        { userId: req.userId, date: todayStr },
        { $set: { tasksCompleted: done, tasksTotal: allTasks.length } },
        { upsert: true }
      );
      io.to(req.userId.toString()).emit('task_updated', { task, done, total: allTasks.length });
    }
    res.json(task);
  } catch (err) { res.status(500).json({ error: err.message }); }
});

app.delete('/api/tasks/:id', auth, async (req, res) => {
  try {
    await Task.findOneAndDelete({ _id: req.params.id, userId: req.userId });
    res.json({ success: true });
  } catch (err) { res.status(500).json({ error: err.message }); }
});

app.post('/api/tasks/generate', auth, async (req, res) => {
  try {
    // Delete today's auto tasks and regenerate
    await Task.deleteMany({ userId: req.userId, dueDate: today(), autoGenerated: true, completed: false });
    await autoGenerateTasks(req.userId);
    const tasks = await Task.find({ userId: req.userId, dueDate: today() }).sort({ priority: 1 });
    res.json(tasks);
  } catch (err) { res.status(500).json({ error: err.message }); }
});

// ── SCHEDULE ROUTES ──────────────────────────────────────────
app.get('/api/schedule', auth, async (req, res) => {
  try {
    const week = req.query.week || getWeek();
    const sch = await Schedule.findOne({ userId: req.userId, week });
    res.json(sch || { slots: [], routine: {} });
  } catch (err) { res.status(500).json({ error: err.message }); }
});

app.post('/api/schedule', auth, async (req, res) => {
  try {
    const { week, slots, routine } = req.body;
    const sch = await Schedule.findOneAndUpdate(
      { userId: req.userId, week: week || getWeek() },
      { $set: { slots, routine } },
      { upsert: true, new: true }
    );
    // Update user weak subject from routine
    if (routine?.weakSubject) {
      await User.findByIdAndUpdate(req.userId, { weakSubject: routine.weakSubject });
    }
    res.json(sch);
  } catch (err) { res.status(500).json({ error: err.message }); }
});

// ── ACHIEVEMENT ROUTES ───────────────────────────────────────
app.get('/api/achievements', auth, async (req, res) => {
  try {
    const achs = await Achievement.find({ userId: req.userId }).sort({ earnedAt: -1 });
    res.json(achs);
  } catch (err) { res.status(500).json({ error: err.message }); }
});

// ── LEADERBOARD ──────────────────────────────────────────────
app.get('/api/leaderboard', auth, async (req, res) => {
  try {
    const pipeline = [
      { $group: { _id: '$userId', totalStudyTime: { $sum: '$studyTime' }, tasksCompleted: { $sum: '$tasksCompleted' }, avgSuccess: { $avg: { $cond: [{ $gt: ['$tasksTotal', 0] }, { $multiply: [{ $divide: ['$tasksCompleted', '$tasksTotal'] }, 100] }, 0] } } } },
      { $sort: { totalStudyTime: -1 } },
      { $limit: 20 },
      { $lookup: { from: 'users', localField: '_id', foreignField: '_id', as: 'user' } },
      { $unwind: '$user' },
      { $project: { name: '$user.name', totalStudyTime: 1, tasksCompleted: 1, avgSuccess: 1 } }
    ];
    const lb = await Progress.aggregate(pipeline);
    res.json(lb.map((u, i) => ({ ...u, rank: i + 1 })));
  } catch (err) { res.status(500).json({ error: err.message }); }
});

// ── MOCK TEST ROUTES ─────────────────────────────────────────
app.post('/api/mocktest', auth, async (req, res) => {
  try {
    const test = await MockTest.create({ ...req.body, userId: req.userId });
    res.json(test);
  } catch (err) { res.status(500).json({ error: err.message }); }
});

app.get('/api/mocktest/history', auth, async (req, res) => {
  try {
    const tests = await MockTest.find({ userId: req.userId }).sort({ completedAt: -1 }).limit(10);
    res.json(tests);
  } catch (err) { res.status(500).json({ error: err.message }); }
});

// ── AI CHAT ROUTE ────────────────────────────────────────────
app.post('/api/chat', auth, async (req, res) => {
  try {
    const { message } = req.body;
    const user = await User.findById(req.userId).select('-password');
    const todayProg = await Progress.findOne({ userId: req.userId, date: today() });
    const stats = await Progress.aggregate([
      { $match: { userId: new mongoose.Types.ObjectId(req.userId) } },
      { $group: { _id: null, total: { $sum: '$studyTime' } } }
    ]);
    const totalHrs = Math.round((stats[0]?.total || 0) / 60);
    const streak = await calcStreak(req.userId);
    const daysLeft = Math.ceil((new Date('2027-01-20') - new Date()) / 86400000);
    const recentChats = await Chat.find({ userId: req.userId }).sort({ timestamp: -1 }).limit(8);

    await Chat.create({ userId: req.userId, role: 'user', content: message });

    const systemPrompt = `You are StudyBot, an expert JEE 2027 AI coach for ${user.name}.

Student Status:
- Days to JEE Mains 2027: ${daysLeft}
- Total study time: ${totalHrs} hours
- Today's study: ${Math.round((todayProg?.studyTime||0)/60*10)/10} hours
- Current streak: ${streak} days
- Weak subject: ${user.weakSubject}

You help with:
1. JEE Physics, Chemistry, Mathematics doubts (class 11-12 level)
2. Study plans and timetables
3. Chapter strategies and important topics
4. Motivation and mindset
5. Progress analysis

Be concise, motivating, and JEE-focused. Use bullet points. Always end with encouragement.`;

    const history = recentChats.reverse().map(c => ({ role: c.role, content: c.content }));
    history.push({ role: 'user', content: message });

    let reply = '';
    const apiKey = process.env.CLAUDE_API_KEY;

    if (apiKey && !apiKey.includes('xxxxx')) {
      try {
        const resp = await axios.post('https://api.anthropic.com/v1/messages', {
          model: 'claude-sonnet-4-20250514',
          max_tokens: 800,
          system: systemPrompt,
          messages: history
        }, { headers: { 'Content-Type': 'application/json', 'x-api-key': apiKey, 'anthropic-version': '2023-06-01' } });
        reply = resp.data.content[0].text;
      } catch (e) { reply = getSmartReply(message, daysLeft, streak, totalHrs); }
    } else {
      reply = getSmartReply(message, daysLeft, streak, totalHrs);
    }

    await Chat.create({ userId: req.userId, role: 'assistant', content: reply });
    res.json({ reply });
  } catch (err) { res.status(500).json({ error: err.message }); }
});

function getSmartReply(msg, daysLeft, streak, totalHrs) {
  const m = msg.toLowerCase();
  if (m.includes('plan') || m.includes('timetable') || m.includes('schedule'))
    return `📅 **Recommended Daily Schedule for JEE 2027**\n\n• 5:00–6:00 AM → Wake up + Revision\n• 6:00–8:00 AM → Mathematics\n• 8:30–10:30 AM → Physics\n• 11:00–1:00 PM → Chemistry\n• 2:00–4:00 PM → PYQ Practice\n• 4:30–6:30 PM → Weak Subject Extra\n• 7:00–9:00 PM → Problem Solving\n• 9:00–10:00 PM → Revision + Notes\n\n🎯 Target **10 hours/day** — You have **${daysLeft} days** left. Every hour counts!`;
  if (m.includes('motivat') || m.includes('tired') || m.includes('give up') || m.includes('fail'))
    return `💪 **Don't give up — you're closer than you think!**\n\nYou've already studied **${totalHrs} hours** and maintained a **${streak}-day streak**. That's real dedication!\n\n• Every JEE topper felt exactly like you right now\n• The pain of discipline is temporary\n• The pride of IIT is forever\n• ${daysLeft} days is MORE than enough if you use them wisely\n\nGet up, drink water, and open your book. Your future self is counting on TODAY! 🚀`;
  if (m.includes('physics'))
    return `⚡ **Physics JEE Strategy**\n\n**Most Important (12+ questions):**\n• Electrostatics & Current Electricity\n• Modern Physics\n• SHM & Waves\n• Optics\n\n**Books:** HC Verma (concepts) + DC Pandey (problems)\n\n**Strategy:**\n• Solve 20 MCQs daily\n• Focus on numerical problems\n• Last 10yr PYQs chapter-wise\n• Revise formulas every morning`;
  if (m.includes('chemistry'))
    return `🧪 **Chemistry JEE Strategy**\n\n**High Scoring:**\n• Organic Chemistry (name reactions, mechanisms)\n• Coordination Compounds\n• Electrochemistry\n• Chemical Equilibrium\n\n**Books:** NCERT (Inorganic) + MS Chauhan (Organic)\n\n**Strategy:**\n• NCERT is Bible for Inorganic — read 3 times\n• Make reaction charts for Organic\n• Solve 30 MCQs daily\n• Sunday full Chemistry revision`;
  if (m.includes('math') || m.includes('maths'))
    return `📐 **Mathematics JEE Strategy**\n\n**Most Important (40%+ weightage):**\n• Calculus (Integration especially)\n• Coordinate Geometry\n• Algebra (Complex Numbers, Matrices)\n• Probability\n\n**Books:** Cengage → Arihant → PYQs\n\n**Strategy:**\n• 25 problems daily minimum\n• Focus on speed + accuracy\n• Integration: practice 10 questions daily\n• Never skip 3D Geometry`;
  if (m.includes('progress') || m.includes('how am i'))
    return `📊 **Your Progress:**\n\n• Total study time: **${totalHrs} hours**\n• Current streak: **${streak} days** 🔥\n• Days left to JEE: **${daysLeft}**\n\n${totalHrs < 50 ? '⚠️ Need to increase hours! Target 300+ hours in next 30 days.' : totalHrs < 200 ? '🎯 Good start! Keep pushing for 500+ total hours.' : '✅ Excellent dedication! Maintain this pace.'}\n\nFocus on weak areas and PYQ practice. You've got this! 💪`;
  return `🤖 **StudyBot here!** I'm your JEE 2027 coach.\n\nYou have **${daysLeft} days** left with a **${streak}-day** study streak. 💪\n\nI can help you with:\n• 📚 Physics, Chemistry, Math doubts\n• 📅 Study plans & schedules\n• 🎯 Chapter strategies\n• 💪 Motivation\n• 📊 Progress analysis\n\nWhat do you need help with?`;
}

// ── SOCKET.IO ─────────────────────────────────────────────────
io.on('connection', socket => {
  socket.on('join', userId => {
    socket.join(userId);
    console.log(`User ${userId} joined`);
  });

  socket.on('study_start', async ({ userId, subject }) => {
    io.to(userId).emit('study_started', { subject, time: Date.now() });
  });

  socket.on('study_end', async ({ userId, minutes, subject }) => {
    try {
      if (minutes < 1) return;
      let p = await Progress.findOne({ userId, date: today() });
      if (!p) p = await Progress.create({ userId, date: today(), studyTime: 0 });
      p.studyTime = (p.studyTime || 0) + minutes;
      await p.save();
      io.to(userId).emit('progress_update', p);
      io.to(userId).emit('study_time_live', { total: p.studyTime, added: minutes });
    } catch (e) { console.error(e); }
  });

  socket.on('disconnect', () => console.log('Socket disconnected'));
});

function getWeek() {
  const n = new Date(), s = new Date(n.getFullYear(), 0, 1);
  return `${n.getFullYear()}-W${String(Math.ceil(((n - s) / 86400000 + s.getDay() + 1) / 7)).padStart(2, '0')}`;
}

app.get('*', (req, res) => res.sendFile(path.join(__dirname, '../Frontend/index.html')));

const PORT = process.env.PORT || 5000;
server.listen(PORT, () => console.log(`\n🚀 StudyUp Server on http://localhost:${PORT}\n`));