const express = require('express');
const http = require('http');
const { Server } = require('socket.io');
const mongoose = require('mongoose');
const cors = require('cors');
const path = require('path');
const bcrypt = require('bcryptjs');
const jwt = require('jsonwebtoken');
const axios = require('axios');
require('dotenv').config();

const app = express();
const server = http.createServer(app);
const io = new Server(server, { cors: { origin: '*', methods: ['GET','POST','PUT','DELETE'] } });

app.use(cors());
app.use(express.json());
app.use(express.static(path.join(__dirname, '../Frontend')));

mongoose.connect(process.env.MONGO_URI || 'mongodb://localhost:27017/studyup')
  .then(() => console.log('✅ MongoDB Connected'))
  .catch(err => console.log('❌ DB Error:', err.message));

const JWT_SECRET = process.env.JWT_SECRET || 'studyup_jee2027_secret';
const today = () => new Date().toISOString().split('T')[0];

// ═══ SCHEMAS ═══
const UserSchema = new mongoose.Schema({
  name: { type: String, required: true },
  email: { type: String, required: true, unique: true },
  password: { type: String, required: true },
  weakSubject: { type: String, default: 'Physics' },
  dailyGoal: { type: Number, default: 8 },
  createdAt: { type: Date, default: Date.now }
});

const ProgressSchema = new mongoose.Schema({
  userId: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
  date: { type: String, required: true },
  studyTime: { type: Number, default: 0 },
  tasksCompleted: { type: Number, default: 0 },
  tasksTotal: { type: Number, default: 0 },
  lecturesDone: { type: Number, default: 0 },
  subjectTime: {
    Physics: { type: Number, default: 0 },
    Chemistry: { type: Number, default: 0 },
    Mathematics: { type: Number, default: 0 }
  }
}, { timestamps: true });

const TaskSchema = new mongoose.Schema({
  userId: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
  title: { type: String, required: true },
  subject: { type: String, required: true },
  chapter: { type: String, default: '' },
  lectures: { type: Number, default: 0 },
  priority: { type: String, default: 'Medium' },
  importance: { type: String, default: 'Important' },
  timeRequired: { type: Number, default: 60 },
  pyqCount: { type: Number, default: 0 },
  dueDate: { type: String },
  completed: { type: Boolean, default: false },
  completedAt: { type: Date },
  autoGenerated: { type: Boolean, default: false }
}, { timestamps: true });

const ScheduleSchema = new mongoose.Schema({
  userId: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
  week: { type: String, required: true },
  slots: [{ day: String, startTime: String, endTime: String, subject: String, chapter: String }],
  routine: { wakeTime: String, sleepTime: String, studyHours: Number, weakSubject: String }
}, { timestamps: true });

const AchievementSchema = new mongoose.Schema({
  userId: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
  title: String, description: String, icon: { type: String, default: '🏆' },
  type: String, xp: { type: Number, default: 10 },
  earnedAt: { type: Date, default: Date.now }
});

const ChatSchema = new mongoose.Schema({
  userId: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
  role: { type: String, enum: ['user','assistant'] },
  content: String,
  timestamp: { type: Date, default: Date.now }
});

const MockTestSchema = new mongoose.Schema({
  userId: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
  score: Number, totalQ: Number, correct: Number, wrong: Number, skipped: Number,
  timeTaken: Number,
  subjectScores: { Physics: Number, Chemistry: Number, Mathematics: Number },
  completedAt: { type: Date, default: Date.now }
});

const User = mongoose.model('User', UserSchema);
const Progress = mongoose.model('Progress', ProgressSchema);
const Task = mongoose.model('Task', TaskSchema);
const Schedule = mongoose.model('Schedule', ScheduleSchema);
const Achievement = mongoose.model('Achievement', AchievementSchema);
const Chat = mongoose.model('Chat', ChatSchema);
const MockTest = mongoose.model('MockTest', MockTestSchema);

// ═══ AUTH MIDDLEWARE ═══
const auth = async (req, res, next) => {
  try {
    const token = req.headers.authorization?.split(' ')[1];
    if (!token) return res.status(401).json({ error: 'No token' });
    const decoded = jwt.verify(token, JWT_SECRET);
    req.userId = decoded.id;
    next();
  } catch { res.status(401).json({ error: 'Invalid token' }); }
};

// ═══ HELPERS ═══
async function calcStreak(userId) {
  const records = await Progress.find({ userId, studyTime: { $gt: 0 } }).sort({ date: -1 }).lean();
  if (!records.length) return 0;
  let streak = 0;
  let check = new Date(); check.setHours(0,0,0,0);
  for (const r of records) {
    const rd = new Date(r.date); rd.setHours(0,0,0,0);
    const diff = Math.round((check - rd) / 86400000);
    if (diff <= 1) { streak++; check = rd; } else break;
  }
  return streak;
}

async function calcRank(userId) {
  const thirtyAgo = new Date(); thirtyAgo.setDate(thirtyAgo.getDate() - 30);
  const results = await Progress.aggregate([
    { $match: { date: { $gte: thirtyAgo.toISOString().split('T')[0] }, studyTime: { $gt: 0 } } },
    { $group: { _id: '$userId', totalTime: { $sum: '$studyTime' } } },
    { $sort: { totalTime: -1 } }
  ]);
  const idx = results.findIndex(r => r._id.toString() === userId.toString());
  return idx === -1 ? results.length + 1 : idx + 1;
}

async function checkAchievements(userId, streak, totalTasks, totalHours) {
  const existing = await Achievement.find({ userId }).select('title');
  const earned = existing.map(a => a.title);
  const newAchs = [];
  const milestones = [
    { title: 'First Step', desc: 'Completed first task!', icon: '🎯', xp: 10, cond: totalTasks >= 1 },
    { title: 'Task Machine', desc: 'Completed 10 tasks!', icon: '✅', xp: 50, cond: totalTasks >= 10 },
    { title: 'On Fire', desc: '3 day streak!', icon: '🔥', xp: 30, cond: streak >= 3 },
    { title: 'Consistency', desc: '7 day streak!', icon: '💪', xp: 100, cond: streak >= 7 },
    { title: 'Discipline', desc: '14 day streak!', icon: '⚡', xp: 200, cond: streak >= 14 },
    { title: 'Regular', desc: '30 day streak!', icon: '📅', xp: 500, cond: streak >= 30 },
    { title: 'Particular', desc: 'Completed daily tasks 5 times!', icon: '🎯', xp: 75, cond: totalTasks >= 5 },
    { title: 'Time Master', desc: 'Studied 8+ hours in a day!', icon: '⏰', xp: 150, cond: totalHours >= 8 },
    { title: '100 Hours Club', desc: 'Total 100 hours studied!', icon: '🏆', xp: 300, cond: totalHours >= 100 },
  ];
  for (const m of milestones) {
    if (m.cond && !earned.includes(m.title)) {
      const a = await Achievement.create({ userId, title: m.title, description: m.desc, icon: m.icon, xp: m.xp, type: 'auto' });
      newAchs.push(a);
    }
  }
  return newAchs;
}

// ═══ REAL SYLLABUS DATA FROM STUDENT NOTES ═══
// Numbers = lectures per chapter (total: Physics=306, Chemistry=225, Math=309)
const SYLLABUS = {
  Physics: [
    { chapter: 'Kinematics', lectures: 21, pyq: 8, time: 90, priority: 'High' },
    { chapter: 'Work Power Energy', lectures: 12, pyq: 6, time: 75, priority: 'High' },
    { chapter: 'EMI', lectures: 13, pyq: 7, time: 90, priority: 'High' },
    { chapter: 'Centre of Mass', lectures: 15, pyq: 7, time: 90, priority: 'High' },
    { chapter: 'Capacitor', lectures: 13, pyq: 8, time: 90, priority: 'High' },
    { chapter: 'Magnetism', lectures: 13, pyq: 7, time: 90, priority: 'High' },
    { chapter: 'Rotational Motion', lectures: 21, pyq: 9, time: 120, priority: 'High' },
    { chapter: 'Current Electricity', lectures: 23, pyq: 11, time: 120, priority: 'High' },
    { chapter: 'Gravitation', lectures: 5, pyq: 5, time: 75, priority: 'Medium' },
    { chapter: 'Electrostatics P1', lectures: 16, pyq: 10, time: 90, priority: 'High' },
    { chapter: 'Electrostatics P2', lectures: 12, pyq: 8, time: 90, priority: 'High' },
    { chapter: 'NLM', lectures: 4, pyq: 5, time: 60, priority: 'Medium' },
    { chapter: 'Friction', lectures: 6, pyq: 4, time: 60, priority: 'Medium' },
    { chapter: 'Elasticity', lectures: 4, pyq: 3, time: 60, priority: 'Low' },
    { chapter: 'Fluid Mechanics', lectures: 11, pyq: 6, time: 75, priority: 'High' },
    { chapter: 'SHM', lectures: 10, pyq: 7, time: 90, priority: 'High' },
    { chapter: 'Wave', lectures: 10, pyq: 6, time: 90, priority: 'High' },
    { chapter: 'Sound Wave', lectures: 7, pyq: 5, time: 75, priority: 'Medium' },
    { chapter: 'Geometric Optics', lectures: 21, pyq: 10, time: 90, priority: 'High' },
    { chapter: 'Modern Physics', lectures: 21, pyq: 11, time: 90, priority: 'High' },
    { chapter: 'Heat Transfer', lectures: 17, pyq: 7, time: 75, priority: 'High' },
    { chapter: 'KTG', lectures: 4, pyq: 4, time: 60, priority: 'Medium' },
    { chapter: 'Thermodynamics', lectures: 3, pyq: 5, time: 75, priority: 'High' },
    { chapter: 'Wave Optics', lectures: 7, pyq: 6, time: 75, priority: 'High' },
  ],
  Chemistry: [
    { chapter: 'Mole Concept', lectures: 14, pyq: 8, time: 90, priority: 'High' },
    { chapter: 'Gaseous State', lectures: 9, pyq: 5, time: 75, priority: 'Medium' },
    { chapter: 'Chemical Equilibrium', lectures: 7, pyq: 7, time: 90, priority: 'High' },
    { chapter: 'Ionic Equilibrium', lectures: 14, pyq: 8, time: 90, priority: 'High' },
    { chapter: 'Thermodynamics Chem', lectures: 18, pyq: 7, time: 90, priority: 'High' },
    { chapter: 'Thermochemistry', lectures: 6, pyq: 5, time: 75, priority: 'Medium' },
    { chapter: 'Solid State', lectures: 10, pyq: 6, time: 75, priority: 'High' },
    { chapter: 'Liquid Solution', lectures: 12, pyq: 7, time: 90, priority: 'High' },
    { chapter: 'Chemical Kinetics', lectures: 19, pyq: 8, time: 90, priority: 'High' },
    { chapter: 'Radioactivity', lectures: 6, pyq: 5, time: 60, priority: 'Medium' },
    { chapter: 'Electrochemistry', lectures: 19, pyq: 9, time: 90, priority: 'High' },
    { chapter: 'Surface Chemistry', lectures: 7, pyq: 4, time: 60, priority: 'Medium' },
    { chapter: 'Periodicity', lectures: 4, pyq: 5, time: 60, priority: 'Medium' },
    { chapter: 'S Block', lectures: 5, pyq: 4, time: 60, priority: 'Medium' },
    { chapter: 'P Block', lectures: 9, pyq: 7, time: 75, priority: 'High' },
    { chapter: 'D Block', lectures: 7, pyq: 6, time: 75, priority: 'High' },
    { chapter: 'Metallurgy', lectures: 9, pyq: 5, time: 75, priority: 'Medium' },
    { chapter: 'Salt Analysis', lectures: 5, pyq: 4, time: 60, priority: 'Medium' },
    { chapter: 'Grignard Reagent', lectures: 8, pyq: 6, time: 75, priority: 'High' },
    { chapter: 'Named Reactions', lectures: 7, pyq: 7, time: 90, priority: 'High' },
    { chapter: 'Carbonyl Compounds', lectures: 2, pyq: 6, time: 75, priority: 'High' },
    { chapter: 'A.P Datta Effect', lectures: 3, pyq: 4, time: 60, priority: 'Medium' },
  ],
  Mathematics: [
    { chapter: 'Logarithm', lectures: 12, pyq: 6, time: 75, priority: 'High' },
    { chapter: 'Quadratic Equations', lectures: 16, pyq: 8, time: 90, priority: 'High' },
    { chapter: 'Sequence & Progression', lectures: 14, pyq: 7, time: 90, priority: 'High' },
    { chapter: 'Trigonometry P1', lectures: 17, pyq: 8, time: 90, priority: 'High' },
    { chapter: 'Trigonometry P2', lectures: 9, pyq: 7, time: 75, priority: 'High' },
    { chapter: 'Sum of Trigonometry', lectures: 10, pyq: 6, time: 75, priority: 'High' },
    { chapter: 'Basic Straight Line', lectures: 26, pyq: 9, time: 120, priority: 'High' },
    { chapter: 'Circle', lectures: 14, pyq: 8, time: 90, priority: 'High' },
    { chapter: 'P & C', lectures: 12, pyq: 7, time: 90, priority: 'High' },
    { chapter: 'Binomial', lectures: 12, pyq: 7, time: 90, priority: 'High' },
    { chapter: 'Set & Relation', lectures: 2, pyq: 4, time: 60, priority: 'Medium' },
    { chapter: 'Function', lectures: 28, pyq: 9, time: 120, priority: 'High' },
    { chapter: 'ITF', lectures: 19, pyq: 8, time: 90, priority: 'High' },
    { chapter: 'Limit', lectures: 16, pyq: 9, time: 90, priority: 'High' },
    { chapter: 'Continuity', lectures: 14, pyq: 7, time: 90, priority: 'High' },
    { chapter: 'Differentiability', lectures: 10, pyq: 6, time: 75, priority: 'High' },
    { chapter: 'MOD', lectures: 9, pyq: 6, time: 75, priority: 'High' },
    { chapter: 'Indefinite Integration', lectures: 18, pyq: 9, time: 120, priority: 'High' },
    { chapter: 'Definite Integration', lectures: 12, pyq: 8, time: 90, priority: 'High' },
    { chapter: 'AOD', lectures: 17, pyq: 8, time: 90, priority: 'High' },
    { chapter: 'AUC', lectures: 9, pyq: 7, time: 75, priority: 'High' },
    { chapter: 'Differential Equation', lectures: 9, pyq: 7, time: 75, priority: 'High' },
    { chapter: 'Matrix', lectures: 9, pyq: 8, time: 90, priority: 'High' },
    { chapter: 'Determinant', lectures: 10, pyq: 8, time: 90, priority: 'High' },
    { chapter: 'Vector', lectures: 22, pyq: 9, time: 90, priority: 'High' },
    { chapter: '3D Geometry', lectures: 8, pyq: 8, time: 90, priority: 'High' },
    { chapter: 'Probability', lectures: 10, pyq: 8, time: 90, priority: 'High' },
    { chapter: 'Complex Numbers', lectures: 18, pyq: 8, time: 90, priority: 'High' },
    { chapter: 'H & D', lectures: 1, pyq: 3, time: 45, priority: 'Low' },
    { chapter: 'Static', lectures: 2, pyq: 3, time: 60, priority: 'Low' },
    { chapter: 'M Logic', lectures: 1, pyq: 2, time: 45, priority: 'Low' },
  ]
};

const TOTAL = { Physics: 306, Chemistry: 225, Mathematics: 309, total: 840 };

function getWeekStr() {
  const n = new Date(), s = new Date(n.getFullYear(), 0, 1);
  return `${n.getFullYear()}-W${String(Math.ceil(((n-s)/86400000+s.getDay()+1)/7)).padStart(2,'0')}`;
}

async function autoGenerateTasks(userId) {
  const todayStr = today();
  const existing = await Task.find({ userId, dueDate: todayStr });
  if (existing.length > 0) return existing;

  const daysLeft = Math.ceil((new Date('2027-01-20') - new Date()) / 86400000);
  const week = getWeekStr();
  const schedule = await Schedule.findOne({ userId, week });
  const dayName = ['Sun','Mon','Tue','Wed','Thu','Fri','Sat'][new Date().getDay()];

  let subjects = ['Physics', 'Chemistry', 'Mathematics'];
  if (schedule?.slots) {
    const ds = [...new Set(schedule.slots
      .filter(s => s.day === dayName && s.subject !== 'Break' && s.subject !== 'Revision')
      .map(s => s.subject))];
    if (ds.length > 0) subjects = ds;
  }

  const completedTasks = await Task.find({ userId, completed: true, autoGenerated: true }).select('chapter subject');
  const completedChapters = completedTasks.map(t => `${t.subject}-${t.chapter}`);
  const newTasks = [];

  for (const subject of subjects) {
    const chapters = SYLLABUS[subject] || [];
    const available = chapters.filter(c => !completedChapters.includes(`${subject}-${c.chapter}`));
    if (!available.length) continue;

    // Sort: High priority first, then most lectures (most important chapters)
    const sorted = available.sort((a, b) => {
      const pa = a.priority === 'High' ? 0 : a.priority === 'Medium' ? 1 : 2;
      const pb = b.priority === 'High' ? 0 : b.priority === 'Medium' ? 1 : 2;
      if (pa !== pb) return pa - pb;
      return b.lectures - a.lectures;
    });

    const pick = sorted[0];
    const lecturesPerDay = Math.max(1, Math.ceil(pick.lectures / Math.max(Math.ceil(daysLeft / 3), 1)));

    // Watch lecture task
    const task = await Task.create({
      userId,
      title: `📺 ${pick.chapter} — Watch ${lecturesPerDay} lecture${lecturesPerDay > 1 ? 's' : ''}`,
      subject, chapter: pick.chapter,
      priority: pick.priority, importance: 'Important',
      lectures: lecturesPerDay,
      timeRequired: lecturesPerDay * 45,
      pyqCount: pick.pyq,
      dueDate: todayStr, autoGenerated: true
    });
    newTasks.push(task);

    // PYQ solve task for high priority chapters
    if (pick.priority === 'High') {
      const pyqTask = await Task.create({
        userId,
        title: `📝 ${pick.chapter} PYQs — Solve ${pick.pyq} questions`,
        subject, chapter: pick.chapter,
        priority: 'High', importance: 'Critical',
        lectures: 0, timeRequired: 60, pyqCount: pick.pyq,
        dueDate: todayStr, autoGenerated: true
      });
      newTasks.push(pyqTask);
    }
  }

  // Daily revision task
  await Task.create({
    userId, title: '🔄 Revision — Previous day chapters',
    subject: 'Physics', chapter: 'Revision',
    priority: 'Medium', importance: 'Important',
    lectures: 0, timeRequired: 60, pyqCount: 0,
    dueDate: todayStr, autoGenerated: true
  });

  return await Task.find({ userId, dueDate: todayStr }).sort({ priority: 1, pyqCount: -1 });
}

// ═══ AUTH ROUTES ═══
app.post('/api/auth/register', async (req, res) => {
  try {
    const { name, email, password } = req.body;
    if (!name || !email || !password) return res.status(400).json({ error: 'All fields required' });
    if (await User.findOne({ email })) return res.status(400).json({ error: 'Email already exists' });
    const hashed = await bcrypt.hash(password, 12);
    const user = await User.create({ name, email, password: hashed });
    const token = jwt.sign({ id: user._id }, JWT_SECRET, { expiresIn: '30d' });
    res.json({ token, user: { id: user._id, name: user.name, email: user.email } });
  } catch (e) { res.status(500).json({ error: e.message }); }
});

app.post('/api/auth/login', async (req, res) => {
  try {
    const { email, password } = req.body;
    const user = await User.findOne({ email });
    if (!user || !await bcrypt.compare(password, user.password))
      return res.status(400).json({ error: 'Invalid credentials' });
    const token = jwt.sign({ id: user._id }, JWT_SECRET, { expiresIn: '30d' });
    res.json({ token, user: { id: user._id, name: user.name, email: user.email } });
  } catch (e) { res.status(500).json({ error: e.message }); }
});

app.get('/api/auth/me', auth, async (req, res) => {
  try {
    res.json(await User.findById(req.userId).select('-password'));
  } catch (e) { res.status(500).json({ error: e.message }); }
});

// ═══ PROGRESS ROUTES ═══
app.get('/api/progress/today', auth, async (req, res) => {
  try {
    let prog = await Progress.findOne({ userId: req.userId, date: today() });
    if (!prog) prog = { studyTime: 0, tasksCompleted: 0, tasksTotal: 0, lecturesDone: 0, date: today() };
    res.json(prog);
  } catch (e) { res.status(500).json({ error: e.message }); }
});

app.put('/api/progress/today', auth, async (req, res) => {
  try {
    const u = req.body;
    if (u.studyTime !== undefined)
      await Progress.findOneAndUpdate({ userId: req.userId, date: today() }, { $inc: { studyTime: u.studyTime } }, { upsert: true });
    if (u.tasksTotal !== undefined)
      await Progress.findOneAndUpdate({ userId: req.userId, date: today() }, { $set: { tasksTotal: u.tasksTotal, tasksCompleted: u.tasksCompleted } }, { upsert: true });
    if (u.lecturesDone !== undefined)
      await Progress.findOneAndUpdate({ userId: req.userId, date: today() }, { $inc: { lecturesDone: u.lecturesDone } }, { upsert: true });
    if (u.subject && u.minutes) {
      const su = {}; su[`subjectTime.${u.subject}`] = u.minutes;
      await Progress.findOneAndUpdate({ userId: req.userId, date: today() }, { $inc: su }, { upsert: true });
    }
    const prog = await Progress.findOne({ userId: req.userId, date: today() });
    io.to(req.userId.toString()).emit('progress_update', prog);
    res.json(prog);
  } catch (e) { res.status(500).json({ error: e.message }); }
});

app.get('/api/progress/stats', auth, async (req, res) => {
  try {
    const history = await Progress.find({ userId: req.userId }).sort({ date: -1 }).limit(30).lean();
    const totalStudyTime = history.reduce((s, p) => s + (p.studyTime || 0), 0);
    const totalTasks = await Task.countDocuments({ userId: req.userId, completed: true });
    const totalLectures = history.reduce((s, p) => s + (p.lecturesDone || 0), 0);
    const validDays = history.filter(p => p.tasksTotal > 0);
    const avgSuccess = validDays.length
      ? validDays.reduce((s, p) => s + (p.tasksCompleted / p.tasksTotal * 100), 0) / validDays.length
      : 0;
    const streak = await calcStreak(req.userId);
    const rank = await calcRank(req.userId);
    const daysToMains = Math.ceil((new Date('2027-01-20') - new Date()) / 86400000);
    const daysToAdv = Math.ceil((new Date('2027-05-17') - new Date()) / 86400000);
    const phTime = history.reduce((s, p) => s + (p.subjectTime?.Physics || 0), 0);
    const chTime = history.reduce((s, p) => s + (p.subjectTime?.Chemistry || 0), 0);
    const maTime = history.reduce((s, p) => s + (p.subjectTime?.Mathematics || 0), 0);
    const totalSubj = Math.max(phTime + chTime + maTime, 1);
    const lectPct = Math.min(100, Math.round(totalLectures / TOTAL.total * 100));
    const dailyLecTarget = Math.ceil(TOTAL.total / Math.max(daysToMains, 1));

    const newAchs = await checkAchievements(req.userId, streak, totalTasks, Math.round(totalStudyTime / 60));
    newAchs.forEach(a => io.to(req.userId.toString()).emit('achievement_unlocked', a));

    res.json({
      totalStudyTime, totalTasks, avgSuccess: Math.round(avgSuccess),
      streak, rank, daysToMains, daysToAdv,
      studyDays: history.filter(p => p.studyTime > 0).length,
      lectureProgress: {
        totalDone: totalLectures,
        totalRemaining: Math.max(0, TOTAL.total - totalLectures),
        dailyTarget: dailyLecTarget,
        pct: lectPct,
        phDaily: Math.ceil(TOTAL.Physics / Math.max(daysToMains, 1)),
        chDaily: Math.ceil(TOTAL.Chemistry / Math.max(daysToMains, 1)),
        maDaily: Math.ceil(TOTAL.Mathematics / Math.max(daysToMains, 1)),
      },
      subjectPct: {
        Physics: Math.round(phTime / totalSubj * 100),
        Chemistry: Math.round(chTime / totalSubj * 100),
        Mathematics: Math.round(maTime / totalSubj * 100)
      }
    });
  } catch (e) { res.status(500).json({ error: e.message }); }
});

app.get('/api/progress/history', auth, async (req, res) => {
  try {
    const days = parseInt(req.query.days) || 7;
    res.json(await Progress.find({ userId: req.userId }).sort({ date: -1 }).limit(days));
  } catch (e) { res.status(500).json({ error: e.message }); }
});

// ═══ SYLLABUS ═══
app.get('/api/syllabus', auth, async (req, res) => {
  res.json({ syllabus: SYLLABUS, totals: TOTAL });
});

// ═══ TASK ROUTES ═══
app.get('/api/tasks', auth, async (req, res) => {
  try {
    const { date, subject, completed } = req.query;
    let query = { userId: req.userId };
    if (subject) query.subject = subject;
    if (completed !== undefined) query.completed = completed === 'true';
    if (date) query.dueDate = date;
    let tasks = await Task.find(query).sort({ priority: 1, pyqCount: -1, createdAt: -1 });
    if (date === today() && tasks.length === 0) tasks = await autoGenerateTasks(req.userId);
    res.json(tasks);
  } catch (e) { res.status(500).json({ error: e.message }); }
});

app.post('/api/tasks', auth, async (req, res) => {
  try {
    const task = await Task.create({ ...req.body, userId: req.userId });
    io.to(req.userId.toString()).emit('task_added', task);
    res.json(task);
  } catch (e) { res.status(500).json({ error: e.message }); }
});

app.put('/api/tasks/:id', auth, async (req, res) => {
  try {
    const task = await Task.findOneAndUpdate(
      { _id: req.params.id, userId: req.userId },
      { $set: req.body }, { new: true }
    );
    if (req.body.completed && task.lectures > 0) {
      await Progress.findOneAndUpdate(
        { userId: req.userId, date: today() },
        { $inc: { lecturesDone: task.lectures } },
        { upsert: true }
      );
    }
    if (req.body.completed) {
      const done = await Task.countDocuments({ userId: req.userId, completed: true });
      const streak = await calcStreak(req.userId);
      const hrsAgg = await Progress.aggregate([
        { $match: { userId: new mongoose.Types.ObjectId(req.userId) } },
        { $group: { _id: null, t: { $sum: '$studyTime' } } }
      ]);
      const hrs = Math.round((hrsAgg[0]?.t || 0) / 60);
      const newAchs = await checkAchievements(req.userId, streak, done, hrs);
      newAchs.forEach(a => io.to(req.userId.toString()).emit('achievement_unlocked', a));
    }
    io.to(req.userId.toString()).emit('task_updated', task);
    res.json(task);
  } catch (e) { res.status(500).json({ error: e.message }); }
});

app.delete('/api/tasks/:id', auth, async (req, res) => {
  try {
    await Task.findOneAndDelete({ _id: req.params.id, userId: req.userId });
    res.json({ success: true });
  } catch (e) { res.status(500).json({ error: e.message }); }
});

// ═══ SCHEDULE ═══
app.get('/api/schedule', auth, async (req, res) => {
  try {
    const week = req.query.week || getWeekStr();
    const sch = await Schedule.findOne({ userId: req.userId, week });
    res.json(sch || { slots: [], routine: null });
  } catch (e) { res.status(500).json({ error: e.message }); }
});

app.post('/api/schedule', auth, async (req, res) => {
  try {
    const { week, slots, routine } = req.body;
    const sch = await Schedule.findOneAndUpdate(
      { userId: req.userId, week: week || getWeekStr() },
      { $set: { slots, routine } },
      { upsert: true, new: true }
    );
    if (routine?.weakSubject) await User.findByIdAndUpdate(req.userId, { weakSubject: routine.weakSubject });
    res.json(sch);
  } catch (e) { res.status(500).json({ error: e.message }); }
});

// ═══ ACHIEVEMENTS ═══
app.get('/api/achievements', auth, async (req, res) => {
  try {
    res.json(await Achievement.find({ userId: req.userId }).sort({ earnedAt: -1 }));
  } catch (e) { res.status(500).json({ error: e.message }); }
});

// ═══ LEADERBOARD ═══
app.get('/api/leaderboard', auth, async (req, res) => {
  try {
    const thirtyAgo = new Date(); thirtyAgo.setDate(thirtyAgo.getDate() - 30);
    const lb = await Progress.aggregate([
      { $match: { date: { $gte: thirtyAgo.toISOString().split('T')[0] } } },
      { $group: { _id: '$userId', totalTime: { $sum: '$studyTime' }, tasksDone: { $sum: '$tasksCompleted' }, lecturesDone: { $sum: '$lecturesDone' } } },
      { $sort: { totalTime: -1 } }, { $limit: 20 },
      { $lookup: { from: 'users', localField: '_id', foreignField: '_id', as: 'user' } },
      { $unwind: '$user' },
      { $project: { name: '$user.name', totalTime: 1, tasksDone: 1, lecturesDone: 1 } }
    ]);
    res.json(lb.map((u, i) => ({ ...u, rank: i + 1 })));
  } catch (e) { res.status(500).json({ error: e.message }); }
});

// ═══ MOCK TEST ═══
app.post('/api/mocktest', auth, async (req, res) => {
  try {
    const test = await MockTest.create({ ...req.body, userId: req.userId });
    await Progress.findOneAndUpdate(
      { userId: req.userId, date: today() },
      { $inc: { studyTime: Math.round((req.body.timeTaken || 1800) / 60) } },
      { upsert: true }
    );
    res.json(test);
  } catch (e) { res.status(500).json({ error: e.message }); }
});

app.get('/api/mocktest/history', auth, async (req, res) => {
  try {
    res.json(await MockTest.find({ userId: req.userId }).sort({ completedAt: -1 }).limit(10));
  } catch (e) { res.status(500).json({ error: e.message }); }
});

// ═══ AI CHAT ═══
app.post('/api/chat', auth, async (req, res) => {
  try {
    const { message } = req.body;
    const user = await User.findById(req.userId).select('-password');
    const todayProg = await Progress.findOne({ userId: req.userId, date: today() });
    const pending = await Task.find({ userId: req.userId, completed: false, dueDate: today() }).limit(5);
    const daysLeft = Math.ceil((new Date('2027-01-20') - new Date()) / 86400000);
    const streak = await calcStreak(req.userId);
    const recentChats = await Chat.find({ userId: req.userId }).sort({ timestamp: -1 }).limit(8);
    const dailyLec = Math.ceil(TOTAL.total / Math.max(daysLeft, 1));

    await Chat.create({ userId: req.userId, role: 'user', content: message });

    const systemPrompt = `You are StudyBot, expert JEE 2027 AI coach for ${user.name}.
Status: ${daysLeft} days to JEE Mains. Study today: ${todayProg?.studyTime||0} min. Tasks: ${todayProg?.tasksCompleted||0}/${todayProg?.tasksTotal||0}. Lectures today: ${todayProg?.lecturesDone||0}/${dailyLec}. Streak: ${streak} days.
Syllabus: Physics 306 lectures, Chemistry 225, Math 309. Total 840. Daily target: ${dailyLec} lectures.
Be concise, motivating, JEE-specific.`;

    const history = recentChats.reverse().map(c => ({ role: c.role, content: c.content }));
    history.push({ role: 'user', content: message });

    let reply = '';
    const apiKey = process.env.CLAUDE_API_KEY;
    if (apiKey && apiKey !== 'your_anthropic_api_key_here') {
      const resp = await axios.post('https://api.anthropic.com/v1/messages',
        { model: 'claude-sonnet-4-20250514', max_tokens: 800, system: systemPrompt, messages: history },
        { headers: { 'Content-Type': 'application/json', 'x-api-key': apiKey, 'anthropic-version': '2023-06-01' } }
      );
      reply = resp.data.content[0].text;
    } else {
      const m = message.toLowerCase();
      if (m.includes('lecture') || m.includes('how many'))
        reply = `📺 **Daily Lecture Target:**\n• Total: 840 lectures remaining\n• Physics: 306 · Chemistry: 225 · Math: 309\n• Days left: ${daysLeft}\n• **Target: ${dailyLec} lectures/day**\n\nPer subject:\n• Physics: ${Math.ceil(306/daysLeft)}/day\n• Chemistry: ${Math.ceil(225/daysLeft)}/day\n• Maths: ${Math.ceil(309/daysLeft)}/day`;
      else if (m.includes('motivat') || m.includes('tired'))
        reply = `💪 **${daysLeft} days. ${dailyLec} lectures/day.**\n\n840 lectures total. Every skipped day = ${dailyLec} extra tomorrow.\n\n🔥 Streak: ${streak} days!\n\nJust open ONE lecture. You'll do more. Go! 🚀`;
      else if (m.includes('plan') || m.includes('schedule'))
        reply = `📅 **Daily Plan (${daysLeft} days left)**\n\n• 5-7 AM → Physics (${Math.ceil(306/daysLeft)} lectures)\n• 7-9 AM → Chemistry (${Math.ceil(225/daysLeft)} lectures)\n• 9-11 AM → PYQ Practice\n• 11-1 PM → Maths (${Math.ceil(309/daysLeft)} lectures)\n• 2-4 PM → Revision\n• 4-6 PM → Mock Test\n• 7-9 PM → Doubts`;
      else
        reply = `🤖 **StudyBot** — ${daysLeft} days to JEE Mains\n\nDaily target: **${dailyLec} lectures**\n• Physics: ${Math.ceil(306/daysLeft)}/day\n• Chemistry: ${Math.ceil(225/daysLeft)}/day\n• Math: ${Math.ceil(309/daysLeft)}/day\n\nStreak: ${streak} days 🔥\nAsk me anything!`;
    }

    await Chat.create({ userId: req.userId, role: 'assistant', content: reply });
    res.json({ reply });
  } catch (e) { res.status(500).json({ error: e.message }); }
});

// ═══ SOCKET.IO ═══
io.on('connection', (socket) => {
  socket.on('join', (userId) => socket.join(userId));
  socket.on('study_start', ({ userId, subject }) => {
    io.to(userId).emit('study_status', { active: true, subject });
  });
  socket.on('study_end', async ({ userId, subject, minutes }) => {
    if (minutes > 0) {
      try {
        const inc = { studyTime: minutes };
        if (['Physics','Chemistry','Mathematics'].includes(subject)) inc[`subjectTime.${subject}`] = minutes;
        await Progress.findOneAndUpdate({ userId, date: today() }, { $inc: inc }, { upsert: true });
        const prog = await Progress.findOne({ userId, date: today() });
        io.to(userId).emit('progress_update', prog);
        io.to(userId).emit('study_status', { active: false });
      } catch(e) {}
    }
  });
});

app.get('*', (req, res) => res.sendFile(path.join(__dirname, '../Frontend/index.html')));

const PORT = process.env.PORT || 5000;
server.listen(PORT, () => {
  console.log(`\n🚀 StudyUp on http://localhost:${PORT}`);
  console.log(`📚 Physics(306) + Chemistry(225) + Math(309) = 840 total lectures`);
  console.log(`🎯 JEE 2027 Ready!\n`);
});